### ISSUE TITLE
建议将开发者工具的wx.request实现拿出来

### ISSUE THREAD

**Issue by bigmeow** [wechat-miniprogram/miniprogram-simulate#1]
其它api都好模拟，唯独request复杂许多，特别是针对微信请求新开发一个请求库的时候，比如我仓库的axios for小程序库。
自己模拟的话感觉这个测试觉得有些自欺欺人，建议将小程序开发者工具的wx.request实现源码剥离放出来（可能需要跨部门协商？）

**Comment by JuneAndGreen** [comment]
开发者工具的实现是提供的类似客户端的接口暴露给基础库调用，所以无法很好的剥离出来。这个测试集更多的是针对自定义组件的单元测试，所以侧重点并不在 wx.request 上。如果希望有真实请求的话，倒是可以使用 request、axios 等现有的 nodejs 端的库来模拟。

如果要过集成测试的话，可以尝试下这个：https://developers.weixin.qq.com/miniprogram/dev/devtools/monkey-test.html

**Comment by bigmeow** [comment]
那只能这样了
