### ISSUE TITLE
About the license of components invoked by this Project.

### ISSUE THREAD

**Issue by Pateny** [wechat-miniprogram/miniprogram-simulate#100]
I noticed that this repository invoke two components"https://www.npmjs.com/package/miniprogram-compiler，and"https://www.npmjs.com/package/miniprogram-exparser?activeTab=readme",but those two components doesn't have a license. We think this may cause some comliance risk.
 So could you sovle this prolem?I also noticed that those two components are also developed by Wechat.Could you add a license for them in NPM?

**Comment by JuneAndGreen** [comment]
miniprogram-compiler@0.2.2 & miniprogram-exparser@2.29.1 has added the MIT license
