### ISSUE TITLE
开启 virtualHost 单测环境中渲染结果与官网描述不一致

### ISSUE THREAD

**Issue by anlyyao** [wechat-miniprogram/miniprogram-simulate#102]
背景：开启 virtualHost。
依赖：miniprogram-simulate 1.5.8、 j-component 1.4.8、miniprogram-exparser 2.29.1
问题：[单测环境中渲染结果与官网描述不一致，自定义组件本身的那个节点仍然存在](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E8%99%9A%E6%8B%9F%E5%8C%96%E7%BB%84%E4%BB%B6%E8%8A%82%E7%82%B9)。
如： 

```html
<!-- custom-component.wxml , 开启 virtualHost -->
<view class="custom-component" style="{{style}}">测试</view>
```

```html
<!-- 页面的 WXML -->
<custom-component class="test" style="color:red;"></custom-component>
```

 ```html
<!-- snapshot -->
<custom-component class="test" >
    <wx-view class="custom-component"  style="color:red; > 测试 </wx-view>
  </custom-component>
```
从 snapshot 渲染结果来看，单测环境中，virtualHost开启后，自定义组件本身的那个节点仍然存在

**Comment by Tidyzq** [comment]
fixed in https://github.com/wechat-miniprogram/j-component/commit/82a2959638aa2498d4774984628116804ef7e434

**Comment by JuneAndGreen** [comment]
已发布：

j-component@1.4.9
miniprogram-simulate@1.5.9
