### ISSUE TITLE
使用comp.triggerLifeTime('ready')或者其他功能时，微信官方api(非wx.xxx)无法成功调用

### ISSUE THREAD

**Issue by dengfenglai0212** [wechat-miniprogram/miniprogram-simulate#103]
如业务侧在ready的生命周期中使用 getCurrentPages()等微信api时，测试不会顺利进行。
![image](https://user-images.githubusercontent.com/51987848/215425300-925114df-49be-4d1a-9065-c04e6ed2cf4a.png)
请问是缺少某些配置么？ 因为小程序项目中不可避免使用微信官方api(非wx.xxx)，感觉不应该不支持才对..

**Comment by JuneAndGreen** [comment]
这是只针对第三方自定义组件的单测，也就是提供了一个组件系统，跑在非微信环境，所有的 wx 等官方特有接口需要自己模拟返回。完整小程序的测试，可使用小程序自动化方案：https://developers.weixin.qq.com/miniprogram/dev/devtools/auto/

**Comment by dengfenglai0212** [comment]
> 这是只针对第三方自定义组件的单测，也就是提供了一个组件系统，跑在非微信环境，所有的 wx 等官方特有接口需要自己模拟返回。完整小程序的测试，可使用小程序自动化方案：https://developers.weixin.qq.com/miniprogram/dev/devtools/auto/ 或者使用云测的自定义测试方案：https://developers.weixin.qq.com/miniprogram/dev/devtools/minitest/
看到了文档中针对wx.xxx的自定义返回，但是非wx的官方接口模拟可以给个简单的例子吗？

**Comment by JuneAndGreen** [comment]
跟 wx 一样，你挂在 global 上就行。

**Comment by JuneAndGreen** [comment]
> > 这是只针对第三方自定义组件的单测，也就是提供了一个组件系统，跑在非微信环境，所有的 wx 等官方特有接口需要自己模拟返回。完整小程序的测试，可使用小程序自动化方案：https://developers.weixin.qq.com/miniprogram/dev/devtools/auto/ 或者使用云测的自定义测试方案：https://developers.weixin.qq.com/miniprogram/dev/devtools/minitest/
> 
> 看到了文档中针对wx.xxx的自定义返回，但是非wx的官方接口模拟可以给个简单的例子吗？


跟 wx 一样，你挂在 global 上就行。
