### ISSUE TITLE
是否支持 selectOwnerComponent

### ISSUE THREAD

**Issue by binggg** [wechat-miniprogram/miniprogram-simulate#104]
自定义组件代码中有使用 `this.selectOwnerComponent`

测试的时候报错
```
 TypeError: this.selectOwnerComponent is not a function
```

请问是否支持该 API 
https://developers.weixin.qq.com/miniprogram/dev/reference/api/Component.html

选取当前组件节点所在的组件实例（即组件的引用者），返回它的组件实例对象（会被 wx://component-export 影响） | 2.8.2
-- | --

选取当前组件节点所在的组件实例（即组件的引用者），返回它的组件实例对象（会被 wx://component-export 影响）	[2.8.2](https://developers.weixin.qq.com/miniprogram/dev/framework/compatibility.html)

**Comment by JuneAndGreen** [comment]
看看依赖的 miniprogram-exparser 是哪个版本，如果版本较低，尝试更新到最新的版本试试？（包括 miniprogram-simulate 和依赖的 j-component 和 miniprogram-exparser）

**Comment by binggg** [comment]
└─┬ miniprogram-simulate@1.5.8
  └─┬ j-component@1.4.8
    └── miniprogram-exparser@2.29.1

**Comment by JuneAndGreen** [comment]
看了下 j-component 确实还没有封装，miniprogram-exparser 倒是更新支持了，我补一下。

**Comment by JuneAndGreen** [comment]
已支持：

j-component@1.4.9
miniprogram-simulate@1.5.9
