### ISSUE TITLE
How config miniprogram-simulate in Alipay mini program

### ISSUE THREAD

**Issue by soyadrianhurtado** [wechat-miniprogram/miniprogram-simulate#106]
Is possible config miniprogram-simulate for Alipay mini program framework

**Comment by JuneAndGreen** [comment]
Sorry, that is not supported.

**Comment by JuneAndGreen** [comment]
Miniprogram-simulate use exparser for implementation, which is the base component framework of wechat miniprogram. 
It is not compatible with alipay miniprogram.

**Comment by soyadrianhurtado** [comment]
Have a idea for implement unit testing for components in alipay mini prigram
