### ISSUE TITLE
自定义组件加载不支持绝对路径

### ISSUE THREAD

**Issue by SheldonLaw** [wechat-miniprogram/miniprogram-simulate#11]
## 复现

![image](https://user-images.githubusercontent.com/16605105/54668863-e7223880-4b2a-11e9-944a-26247a937b0b.png)

![image](https://user-images.githubusercontent.com/16605105/54668890-f903db80-4b2a-11e9-8c58-19849f7a1714.png)

## 预期

页面配置文件中的/components/coupon/coupon是绝对路径，应该直接使用，目前转化为：subpages/whole_module/pages/buy/components/coupon/coupon，导致找不到组件。

**Comment by JuneAndGreen** [comment]
是指按照小程序目录的绝对路径的方式吧？反馈收到，后面会规划支持一下。如果有兴趣帮忙完善特性的话，也欢迎来提 pr 哈～

**Comment by katoto** [comment]
我这边也是，完全不按绝对路径来，有偏差。 “invalid componentPath” 这个路径和目录对不上

**Comment by JuneAndGreen** [comment]
已支持。

**Comment by wangQiaoBrother** [comment]
配置 jest moduleNameMapper属性就可以了 https://jestjs.io/zh-Hans/docs/configuration#modulenamemapper-objectstring-string--arraystring
