### ISSUE TITLE
在调用comp.detach()后. jest测试框架 的test函数无效. 报错:NotFoundError: The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by missannil** [wechat-miniprogram/miniprogram-simulate#110]
test("detached周期后,实例取消监控store变化", () => {
    comp.detach();
   // 报错:NotFoundError: The node to be removed is not a child of this node.
    
    expect(11).toBe(11); // 无意义的代码
  });
![image](https://github.com/wechat-miniprogram/miniprogram-simulate/assets/55321481/d4757ce5-976f-480d-ac37-23fbeda41747)

**Comment by missannil** [comment]
如何测试detached后运行的代码正确性？
是否可以在detach函数中加入回调函数等方法来处理这个问题。当前只要调用了comp.detach。jest直接报错了，后续代码无意义了。

**Comment by missannil** [comment]
当前被迫解决方案
![image](https://github.com/wechat-miniprogram/miniprogram-simulate/assets/55321481/440731ec-39f6-4f62-b41c-3256abf38e59)

jest 终端截图
![image](https://github.com/wechat-miniprogram/miniprogram-simulate/assets/55321481/2cb8945d-9c09-473f-804d-9fafe223d7bf)

**Comment by JuneAndGreen** [comment]
我这样试了下貌似没有出现你说的问题，有没有具体的 demo？

<img width="637" alt="image" src="https://github.com/wechat-miniprogram/miniprogram-simulate/assets/7931744/e1b6e75d-29f0-44e9-a6f2-441b7254868b">

<img width="616" alt="image" src="https://github.com/wechat-miniprogram/miniprogram-simulate/assets/7931744/df289180-7e64-45ce-b9c0-fdd9476b921a">

**Comment by missannil** [comment]
https://github.com/wechat-miniprogram/miniprogram-simulate/issues/110#issuecomment-1886645233

> 我这样试了下貌似没有出现你说的问题，有没有具体的 demo？
> 
> <img alt="image" width="637" src="https://private-user-images.githubusercontent.com/7931744/295849909-e1b6e75d-29f0-44e9-a6f2-441b7254868b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjcwMjksIm5iZiI6MTcwNDk2NjcyOSwicGF0aCI6Ii83OTMxNzQ0LzI5NTg0OTkwOS1lMWI2ZTc1ZC0yOWYwLTQ0ZTktYTZmMi00NDFiNzI1NDg2OGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDk1MjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQzMDgxZDgxOTAxNDkxZjg5ZjlmOGI4MzBhNjhjMDEyMDQ3ODk3MmM4YTg2NjBhNWE4NmJkOGZjZTFiMzQxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Egl1cb0aGveU4xn7lPOJLSZcD-hW-MYAQFw01038d2Q"> <img alt="image" width="616" src="https://private-user-images.githubusercontent.com/7931744/295850048-df289180-7e64-45ce-b9c0-fdd9476b921a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjcwMjksIm5iZiI6MTcwNDk2NjcyOSwicGF0aCI6Ii83OTMxNzQ0LzI5NTg1MDA0OC1kZjI4OTE4MC03ZTY0LTQ1Y2UtYjljMC1mZGQ5NDc2YjkyMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDk1MjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTc5Y2Q1YjZkOWE4YTI3ZjdlNjQxZmE3ZjhkZDFiYmFiOGFhMjFjZTI1ZjJhZjg5NDkxODVhZjM0YzVjN2E0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aWoL4Rd-0Mi-q2qII1vBKnlNJF0w9OUzDg_DzP6xARw">



> 我这样试了下貌似没有出现你说的问题，有没有具体的 demo？
> 
> <img alt="image" width="637" src="https://private-user-images.githubusercontent.com/7931744/295849909-e1b6e75d-29f0-44e9-a6f2-441b7254868b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjcwMjksIm5iZiI6MTcwNDk2NjcyOSwicGF0aCI6Ii83OTMxNzQ0LzI5NTg0OTkwOS1lMWI2ZTc1ZC0yOWYwLTQ0ZTktYTZmMi00NDFiNzI1NDg2OGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDk1MjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQzMDgxZDgxOTAxNDkxZjg5ZjlmOGI4MzBhNjhjMDEyMDQ3ODk3MmM4YTg2NjBhNWE4NmJkOGZjZTFiMzQxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Egl1cb0aGveU4xn7lPOJLSZcD-hW-MYAQFw01038d2Q"> <img alt="image" width="616" src="https://private-user-images.githubusercontent.com/7931744/295850048-df289180-7e64-45ce-b9c0-fdd9476b921a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjcwMjksIm5iZiI6MTcwNDk2NjcyOSwicGF0aCI6Ii83OTMxNzQ0LzI5NTg1MDA0OC1kZjI4OTE4MC03ZTY0LTQ1Y2UtYjljMC1mZGQ5NDc2YjkyMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDk1MjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTc5Y2Q1YjZkOWE4YTI3ZjdlNjQxZmE3ZjhkZDFiYmFiOGFhMjFjZTI1ZjJhZjg5NDkxODVhZjM0YzVjN2E0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aWoL4Rd-0Mi-q2qII1vBKnlNJF0w9OUzDg_DzP6xARw">

感谢您的回答，我的问题，关闭了
