### ISSUE TITLE
无法测试报错的情形啊

### ISSUE THREAD

**Issue by missannil** [wechat-miniprogram/miniprogram-simulate#111]
describe("RootComponent-events", () => {
  const id = simulate.load(path.resolve(__dirname, "IsPage"));
  const comp = simulate.render(id);
  const parent = document.createElement("parent-wrapper");

  test("xxxx", () => {
    try {
      comp.attach(parent);
    } catch (error) {
      expect(() => error).toBe("组件构建挂载过程中报错信息");
    }
  });
});

想测试一个插件，当语法字段不对时报错，控制台报错了，但却无法catch中获取错误

即： comp.attach(parent);  无法提供构建中报错的问题。

**Comment by JuneAndGreen** [comment]
wxml 编译？

那是在 load 的阶段做的。
