### ISSUE TITLE
能否加入在使用Component API 建立page时,可测试页面组件特性

### ISSUE THREAD

**Issue by missannil** [wechat-miniprogram/miniprogram-simulate#113]
比如 允许配置中加入isPage：true时，插件会判断我当前要建立的组件是页面实例，从而实现页面特性(比如实例下的is字段 route字段)

1. 页面生命周期函数，比如onLoad(官方让在methods中写入)

2. 因为页面也是组件所以即使作为页面的实例，pageLifetimes中的load(glass-easel支持)依然可以调用。

**Comment by JuneAndGreen** [comment]
这个工具的初衷是设想自定义组件可能作为 npm 包提供给开发者接入而提供的，方便 npm 包提供方做一些单元测试。

页面应该很少这种情况，你是想要集成测试？开发者工具有提供一个自动化测试能力：https://developers.weixin.qq.com/miniprogram/dev/devtools/auto/ 可以做集成测试
