### ISSUE TITLE
发现BUG 初始化组件时如果如果传入的字符串类型则不能正确触发 observer

### ISSUE THREAD

**Issue by kami1983** [wechat-miniprogram/miniprogram-simulate#14]
// 举例来说，这是一个组件的properties 
properties: {
    title: {
      type: String,
      value: '设置title 属性改变这里的值 3',
      observer: function(newVal, oldVal) { //数据监听
        console.log('Properties observer starting ... ')
        console.log(newVal, oldVal)
      }
    }
}

// 如果传入的值是String 类型，则不能正确触发上面的 observer
let comp = simulate.render(myid, {
        title: 'MyName'
})

// 但是如果传入的值是数组，则可以正确触发 observer 事件
let comp = simulate.render(myid, {
        title: ['MyName']
        
})

**Comment by JuneAndGreen** [comment]
将 j-component 依赖更新到 1.1.2 应该就能解决这个问题了。
