### ISSUE TITLE
问题，函数作用域中无法正常使用behaviors 定义的对象，这个和实际小程序的运行不一致！

### ISSUE THREAD

**Issue by kami1983** [wechat-miniprogram/miniprogram-simulate#15]
函数作用域中无法正常使用behaviors 定义的对象，这个和实际小程序的运行不一致！

**Comment by kami1983** [comment]
这的确是个BUG，我特意的测试了一下组件的 lifetimes ，在JEST 下组件执行的顺序是 properties.observer{} 先执行 lifetimes.created{} 后执行，导致行为函数无法在observer 中使用。

特意到微信开发者工具上试验了一下，lifetimes.created{} 是先于 properties.observer{} 触发的。这就导致了模拟器与测试环境不一致。

**Comment by JuneAndGreen** [comment]
和 #14 是同一个原因引发的，将 j-component 依赖更新到 1.1.2 应该就能解决这个问题了。
