### ISSUE TITLE
问题:properties中的observer不调用

### ISSUE THREAD

**Issue by Xuemuyang** [wechat-miniprogram/miniprogram-simulate#17]
```
const comp = simulate.render(id, {
      observerCall: true
    }); // 渲染自定义组件
```

```
observerCall: {
      type: Boolean,
      value: false,
      observer(val) {
        this.setData({
          observerCalled: true
        });
      }
    },
```

之后打印data属性，发现没有`observerCalled`属性

**Comment by JuneAndGreen** [comment]
补了相关测试用例，但是没能发现你的问题：https://github.com/wechat-miniprogram/miniprogram-simulate/tree/b39fdb522b211b38c195fba36970ebd0c1038677/test/comp5

能否提供以下能复现问题的完整 demo？

**Comment by kami1983** [comment]
我觉得上面补充的测试并没有测试到 properties ，比如如下的代码就不运行

const id_oper = simulate.load(path.join(__dirname, 'PMElasticFrame'))
let comp = simulate.render(id_oper, {
   elasticFrameType: '理想'
})

// ---------------

Component({
  behaviors: [],
  behaviors: [],
  properties: {
    elasticFrameType: {
      type: Boolean, // 验证类型
      value: false, //默认值
      observer: function(newVal, oldVal) {
         console.log('触发了么？并没有')
      }
    },
.... ....
})

**Comment by zyziyun** [comment]
如果在observer里面有内置函数调用（非setData）就会报错，比如 this.selectAllComponents 这个，就会报错，因为this上没有selectAllComponents这个函数

**Comment by JuneAndGreen** [comment]
@kami1983 你这个是初始化时传的 properties 吧，并不是传给子组件的 properties ？

**Comment by JuneAndGreen** [comment]
@zyziyun observer 里是有 selectAllComponents 方法的，你看下是不是用的版本比较旧？

**Comment by JuneAndGreen** [comment]
@kami1983  这个测试用例应该是你说的那个场景：https://github.com/wechat-miniprogram/miniprogram-simulate/tree/3aa330a34a2edfdf97cbed995632d84df43ed6ef/test/comp1
