### ISSUE TITLE
【自定义tabBar有2个BUG】

### ISSUE THREAD

**Issue by dagang007** [wechat-miniprogram/miniprogram-simulate#20]
https://developers.weixin.qq.com/community/develop/doc/000e86cbba4668942868327e751000

**Comment by dagang007** [comment]
结论：原生tabBar可以覆盖webview，自定义tarBar不可以（真机上微信V7）

**Comment by JuneAndGreen** [comment]
小程序相关问题请提到到微信开放社区里。
