### ISSUE TITLE
组件中使用 import 方式引入模块报错

### ISSUE THREAD

**Issue by nyaapass** [wechat-miniprogram/miniprogram-simulate#22]
因为原生小程序代码只要开启 `ES6 转 ES5` 选项就可以通过 `import` 方式引入代码, 所以一直没有加上 `Babel`

但是使用该测试工具集测试含有 `import` 语句的组件时, 就会报如下错误:

```
import util from '../../utils/util';
           ^^^^

SyntaxError: Unexpected identifier
```

**Comment by JuneAndGreen** [comment]
在 node 上跑 miniprogram-simulate 可以理解为就是使用 require 来跑组件 js 的，miniprogram-simulate 本身只是一个工具，你需要在框架层面上支持 es6 语法才行。
