### ISSUE TITLE
miniprogram-exparser可以提供个源码么，我这边一直在报错想调试一下

### ISSUE THREAD

**Issue by zyziyun** [wechat-miniprogram/miniprogram-simulate#24]
现在是编译过的版本，感谢感谢~

**Comment by JuneAndGreen** [comment]
抱歉，暂未获得提供源码的许可，故无法提供。

**Comment by Genuifx** [comment]
多层嵌套组件也遇到报错了

`TypeError: Cannot read property '_unprepared' of undefined`

希望 exparser 早日开源维护

**Comment by Genuifx** [comment]
发现问题在于组件使用了默认表单的behavior`'wx://form-field'`，请问simulate可以添加一下相关支持吗？这里加一个默认的 behavior，同样的问题应该也发生在另外一个内置的behavior`wx://component-export
`
