### ISSUE TITLE
当调用render后再次调用render报错

### ISSUE THREAD

**Issue by 5kinna** [wechat-miniprogram/miniprogram-simulate#25]
版本号为：
"j-component":的版本号为："^1.1.2"，
"miniprogram-simulate": 的版本号为："^1.0.1"

部分代码如下：
describe('badge render', () => {
  it('default', () => {
    const componentId =simulate.load('index', 'comp')
    const component =simulate.render(componentId, {})
    const parent = document.createElement('parent-wrapper')
    component.attach(parent)
    expect(component).toMatchSnapshot()
  })
  it('dot', () => {
    const componentId = simulate.load('index', 'comp')
    const component =simulate.render(componentId, {dot: true})
    const parent = document.createElement('parent-wrapper-dot')
    component.attach(parent)
    expect(component).toMatchSnapshot()
  })
})

结果为：
先调用一次render之后再调用render的时候，id为undefined，会报错。

**Comment by zhc525349965** [comment]
遇到了同样的问题，不知道什么时候解决？

**Comment by Genuifx** [comment]
同复现了问题

**Comment by Genuifx** [comment]
初步定位是`require.cache`没有被清除，然后新的组件无法重新调用Component方法进行注册，进而导致无法render

**Comment by JuneAndGreen** [comment]
请问是使用 jest 么？如果是 jest 的话，得用 `jest.resetModules()` 的方式重置模块：https://github.com/facebook/jest/issues/5120

**Comment by JuneAndGreen** [comment]
一般 nodejs 中 `delete require.cache[xxxx]` 是能正常工作的，但是部分测试框架会封装这个依赖系统，导致  `delete require.cache[xxxx]` 不生效。
