### ISSUE TITLE
wxss中使用@important报错

### ISSUE THREAD

**Issue by TellMeY76** [wechat-miniprogram/miniprogram-simulate#27]
版本号为：
"j-component":的版本号为："^1.1.2"，
"miniprogram-simulate": 的版本号为："^1.0.2"

现象为：
当wxss中使用@important引入其他wxss后，会报语法错误 CssSyntaxError: <css input>:9:1: Unexpected }

**Comment by TellMeY76** [comment]
仅在npm test的时候会出现这个错误，编译及上传时未出现

**Comment by JuneAndGreen** [comment]
@import 和 !important 上有支持的，你是写成 @important 了？

参考测试用例：https://github.com/wechat-miniprogram/miniprogram-simulate/blob/master/test/unit/wxss.test.js#L5

**Comment by TellMeY76** [comment]
> @import 和 !important 上有支持的，你是写成 @Important 了？
> 
> 参考测试用例：https://github.com/wechat-miniprogram/miniprogram-simulate/blob/master/test/unit/wxss.test.js#L5

我用的是@import，后来发现如果@import后面不跟空格就不会报错

**Comment by JuneAndGreen** [comment]
https://github.com/wechat-miniprogram/miniprogram-simulate/blob/master/test/unit/wxss/index.wxss

可以提供一下出错 demo 么？我这边的用例就是跟了空格的。
