### ISSUE TITLE
单元测试如何模拟小程序的原生Picker组件？

### ISSUE THREAD

**Issue by IceApriler** [wechat-miniprogram/miniprogram-simulate#3]
您好，由于小程序的Picker是半封装的，用起来不够友好，所以我在其基础上又加了一层封装。但是现在不知道该怎么单元测试，不知道如何模拟用户改变原生Picker的状态，比如滑动column、点击确定等，不知道您能否提供一个思路呢。

**Comment by JuneAndGreen** [comment]
你封装 picker 的时候，应该不需要感知 picker 的滑动之类的吧，应该只需要感知 picker 给你的事件。你模拟时通过某个接口去触发 picker 应该给你的事件来测试你的封装应该就可以的。

**Comment by IceApriler** [comment]
好的，谢谢了
