### ISSUE TITLE
【bug】官方示例karma-coverage测试代码覆盖率为空

### ISSUE THREAD

**Issue by victoryboss** [wechat-miniprogram/miniprogram-simulate#31]
官方示例karma-coverage测试代码覆盖率为空。
(用jest测覆盖率也有问题，官方测试覆盖率为 src 下的代码，并不是test目录组件代码)
以下为配置:
`reporters: ['progress', 'coverage'],
      coverageReporter: {
          type: 'html',
          dir: 'coverage/'
      },`
希望官方修复下

**Comment by JuneAndGreen** [comment]
这个仓库的覆盖率测试\单元测试都是针对这个工具的功能，所以肯定是 src 下的代码。你说的是使用这个工具时对对应组件的覆盖率测试，这个在使用时自己做好配置即可。

**Comment by victoryboss** [comment]
请问官方可以出一下用karma测试覆盖率的代码吗？

**Comment by JuneAndGreen** [comment]
karma 覆盖率有官方插件可用，这里就不提供了： https://github.com/karma-runner/karma-coverage

**Comment by victoryboss** [comment]
好的，谢谢，祝您工作顺利！
