### ISSUE TITLE
observer触发setData正常，但是dom没有更新

### ISSUE THREAD

**Issue by landn172** [wechat-miniprogram/miniprogram-simulate#32]
测试版本：**1.0.8**
代码如下：
![image](https://user-images.githubusercontent.com/4362412/62928303-df6d7400-bdea-11e9-9745-dbc5e24c8a51.png)
测试代码：
![image](https://user-images.githubusercontent.com/4362412/62928560-56a30800-bdeb-11e9-88cb-8fa92865b4b2.png)

```ts
expect(that.data.lineColor).toBe('#df3348'); // 测试通过
expect(that.data.textColor).toBe('#df3348'); // 测试通过
simulate.match(dom); // 测试不通过，dom没有改变： <wx-text class="t-text-line--t-text-line" style="text-decoration: line-through dashed #666666; color: #666666;"></wx-text>
```

**Comment by JuneAndGreen** [comment]
写了个 demo 没有复现（https://github.com/wechat-miniprogram/miniprogram-simulate/tree/master/test/comp6），请检查下写法是否有问题。如果没有的话请给一下能完整能够复现问题的 demo，我这边来调试一下。
