### ISSUE TITLE
 invalid componentPath 找不到组件

### ISSUE THREAD

**Issue by smilebuz** [wechat-miniprogram/miniprogram-simulate#33]
找不到component的路径
![image](https://user-images.githubusercontent.com/13402508/63221165-b9b7e480-c1c7-11e9-9a5f-87f8216f8356.png)
报错信息
![image](https://user-images.githubusercontent.com/13402508/63221224-7e69e580-c1c8-11e9-8497-71ef61a499dc.png)

查看了issue [#9](https://github.com/wechat-miniprogram/miniprogram-simulate/issues/9)
其中的方法没有用 并且也没有说清最后如何解决

版本信息:
`jest`: "^24.9.0",
`miniprogram-simulate`: "^1.0.8"
`miniprogram-compiler`: "^0.1.1"

请问可能会是什么原因呢 麻烦查看一下
谢谢！

**Comment by pbestz** [comment]
你好，这个问题怎么解决的？

**Comment by pbestz** [comment]
遇到了同样的情况，查看demo组件文件名称都是`index.wxml`，`index.json`...，我测试的项目组件文件名并不是`index`，尝试了下将路径指定到文件名级别就可以正常识别了。
