### ISSUE TITLE
wxml中包含的wxs使用src引入的时候，报错

### ISSUE THREAD

**Issue by SeanerJock** [wechat-miniprogram/miniprogram-simulate#35]
我的wxml中有
<wxs module="imgRoot" src="../../../../../common/wxs/imgRoot.wxs" />
使用simulate.load加载控件的时候提示imgRoot.wxs not found

**Comment by JuneAndGreen** [comment]
更新 miniprogram-simulate 和其依赖的 miniprogram-compiler 到最新版本即可，这里必须使用官方的编译器，参考 demo：https://github.com/wechat-miniprogram/miniprogram-simulate/tree/master/test/comp7
