### ISSUE TITLE
子组件 querySelector 获取不到组件实例

### ISSUE THREAD

**Issue by iou90** [wechat-miniprogram/miniprogram-simulate#44]
``` html
<view class="parent">
  <view class="child" />
</view>
```

``` javascript
const parentComponent = rootComponent.querySelector('.parent');
const childComponent = parentComponent.querySelector('.child'); // undefined
// but rootComponent.querySelector('.child'); // Component instance
```

**Comment by JuneAndGreen** [comment]
因为 .child 是在 rootComponent 的 shadow tree 下，而不是在 .parent 的 shadow tree 下，你调 `rootComponent.querySelector('.child');` 试试，小程序的组件系统是参考 web component 的概念实现的。

**Comment by iou90** [comment]
@JuneAndGreen 
我的 comment 里就有写了，这个是符合预期的，但是想知道除了 dom match 外，还有什么办法来写模板结构的测试吗。
expect(\\ child was a child element of parent).toBeTrue()

**Comment by JuneAndGreen** [comment]
因为这里可以拿到 dom 结构，所以第三方通过 dom 结构进行测试的应该都可用。至于组件实例本身的测试，因为没有对外披露小程序组件在 webview 端的具体实现，所以只能检测它能否 slelect 到子组件/data 是否正常等有对外的接口/属性。
