### ISSUE TITLE
querySelector只支持class和id选择器吗

### ISSUE THREAD

**Issue by scriptchao** [wechat-miniprogram/miniprogram-simulate#46]
如题

**Comment by JuneAndGreen** [comment]
querySelector 是小程序基础库实现的接口，具体支持的选择器同这里：https://developers.weixin.qq.com/miniprogram/dev/api/wxml/SelectorQuery.select.html

**Comment by scriptchao** [comment]
看了下 不支持标签选择器  所有需要选择的组件必须写上class或者id  很不友好哦
