### ISSUE TITLE
invalid componentPath: /dist/components/coupon-wx/index

### ISSUE THREAD

**Issue by leo4developer** [wechat-miniprogram/miniprogram-simulate#47]
为什么直接写绝对路径会报错？
![{A46D36ED-D31A-47D7-81A2-F3D0A68080F9}_20200205144834 - 副本](https://user-images.githubusercontent.com/15160478/73818257-ed470380-4827-11ea-9566-e07fa5ea191f.jpg)
![{7C5CF707-63E5-4137-80AB-1B93D57F30D1}_20200205145120 - 副本](https://user-images.githubusercontent.com/15160478/73818262-efa95d80-4827-11ea-8b61-f16f3b9ae326.jpg)

**Comment by wangQiaoBrother** [comment]
配置 jest moduleNameMapper属性就可以了 https://jestjs.io/zh-Hans/docs/configuration#modulenamemapper-objectstring-string--arraystring
