### ISSUE TITLE
使用内置 behaviors--- behaviors: ['wx://component-export']报错

### ISSUE THREAD

**Issue by wangjgweb** [wechat-miniprogram/miniprogram-simulate#50]
自定义组件中使用内置behaviors，behaviors: ['wx://component-export'] ， 单测报错
TypeError: Cannot read property '_unprepared' of undefined；
现在支持使用内置 behaviors嘛？

**Comment by JuneAndGreen** [comment]
wx://component-export 已支持： miniprogram-simulate@1.2.0

相关测试用例：https://github.com/wechat-miniprogram/j-component/blob/db425fe3e4edda4b75532663cd88ce5a16e19c28/test/component.test.js#L571

**Comment by SevenOutman** [comment]
`behavior: ['wx://form-field-group']` 遇到同样错误

**Comment by JuneAndGreen** [comment]
> `behavior: ['wx://form-field-group']` 遇到同样错误

miniprogram-simulate@1.4.2 已支持
