### ISSUE TITLE
wxss的getImportList函数遇到多个import语句时，只能匹配第一个

### ISSUE THREAD

**Issue by wendychengc** [wechat-miniprogram/miniprogram-simulate#51]
wxss文件形如

```
@import '../common/common.wxss';
@import '../sub/sub.wxss';
.index {
  color: green;
}
```
使用代码中的正则表达式进行匹配时
`const reg = /@import\s+(?:(?:"([^"]+)")|(?:'([^"]+)'));/ig`

由于贪婪匹配规则，第一次就会匹配为

../common/common.wxss';\r\n@import '../sub/sub.wxss

则第二个import文件无法正确匹配。

建议修改为
const reg = /^@import\s+(?:(?:"([^"]+)")|(?:'([^']+)'));$/gmi
使用m声明多行模式，用^和$匹配行头行尾，这样每个文件都能匹配到了

**Comment by JuneAndGreen** [comment]
这里是使用正则的 exec 方法一个一个找出来的，不需要声明多行模式应该也可以的：https://github.com/wechat-miniprogram/miniprogram-simulate/blob/master/src/wxss.js#L39

参考测试用例：https://github.com/wechat-miniprogram/miniprogram-simulate/blob/master/test/unit/wxss.test.js

**Comment by JuneAndGreen** [comment]
你这个问题明确了，并不是多行匹配的问题，是正则里对单引号处理不对，在 1.2.2 版本已 fixed。
