### ISSUE TITLE
boundingClientRect问题

### ISSUE THREAD

**Issue by juzi214032** [wechat-miniprogram/miniprogram-simulate#52]
组件内部使用 boundingClientRect 获取了某个节点的位置信息，但是使用miniprogram-simulate测试组件内的方法时，获取到的节点信息宽高都是0

**Comment by Tidyzq** [comment]
https://github.com/jsdom/jsdom/issues/653 jsdom本身没有实现布局引擎，因此 getBoundingClientRect 返回都是 0。
可以将环境从 jsdom 改为 puppeteer 等真实浏览器环境来解决。

**Comment by Damoness** [comment]
> [jsdom/jsdom#653](https://github.com/jsdom/jsdom/issues/653) jsdom本身没有实现布局引擎，因此 getBoundingClientRect 返回都是 0。 可以将环境从 jsdom 改为 puppeteer 等真实浏览器环境来解决。

好改吗
