### ISSUE TITLE
无法获取子组件的元素

### ISSUE THREAD

**Issue by wangxianfa** [wechat-miniprogram/miniprogram-simulate#53]
// chiild.js
`<view class="child"></view>`

//index.test.js
childid = simulate.load(child),
id = simulate.load({
            template: `<child  title="xxx"></child>`,
            usingComponents: {
                child: childid
            }
   });
comp = simulate.render(id);
comp.querySelector('.child'); 
class为child的 dom元素无法获取到，打印出的comp.dom.innerHTML是存在的，`<child><wx-view class="child--child"></wx-view></child>`

通过comp.querySelector('.child--child')页无法获取到

**Comment by Tidyzq** [comment]
child 组件和使用它的组件（称其为 parent 组件）的 shadowTree 是隔离的，querySelector默认不能穿透 shadowTree 从 parent 组件去选择到 child 组件中。
在这个例子中要实现获取到 `<view class="child"></view>` 可以通过在 parent 组件中设置 `<child class="child1" title="xxx" />`，然后通过 `comp.querySelector('.child1').querySelector('.child')` 获取
