### ISSUE TITLE
wxml中包含的wxs使用src引入的时候，官方声明修复后依旧报错

### ISSUE THREAD

**Issue by hadeshe93** [wechat-miniprogram/miniprogram-simulate#54]
更新 miniprogram-simulate 和其依赖的 miniprogram-compiler 到最新版本即可，这里必须使用官方的编译器，参考 demo：https://github.com/wechat-miniprogram/miniprogram-simulate/tree/master/test/comp7

_Originally posted by @JuneAndGreen in https://github.com/wechat-miniprogram/miniprogram-simulate/issues/35#issuecomment-556043542_

**Comment by hadeshe93** [comment]
上面官方给出的例子是引入组件当前路径下的 wxs 模块，一旦将 wxs 模块抽离到外面，使用相对路径引入，例如 `src="../../wxs/tools.wxs"` 就依然会在运行测试用例时，报错找不到该 wxs 模块。

**Comment by JuneAndGreen** [comment]
https://github.com/wechat-miniprogram/miniprogram-simulate/blob/master/docs/api.md#loadcomponentpath-tagname-options--loaddefinition

![image](https://user-images.githubusercontent.com/7931744/83262495-ab373880-a1ef-11ea-88e0-2c93ddcb8738.png)

配一下 rootPath，默认取组件所在目录作为项目根目录，文件必须都在项目根目录下。
