### ISSUE TITLE
自定义组件加载不支持绝对路径，官方声明已支持后仍稳定复现

### ISSUE THREAD

**Issue by hadeshe93** [wechat-miniprogram/miniprogram-simulate#55]
已支持。

_Originally posted by @JuneAndGreen in https://github.com/wechat-miniprogram/miniprogram-simulate/issues/11#issuecomment-615225713_

**Comment by hadeshe93** [comment]
自定义组件的 json 文件中使用 `usingComponents` 中使用绝对路径引入其它自定义组件，在运行单测时依旧报错找不到相对应的组件，不知道这一点是不是还没支持？

```
{
"devDependencies": {
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.9.6",
    "babel-jest": "^26.0.1",
    "miniprogram-automator": "^0.9.1",
    "miniprogram-simulate": "^1.2.2",
    "sinon": "^9.0.2"
  }
}
```

**Comment by JuneAndGreen** [comment]
原先是支持了文件系统的绝对路径，现在改为相对项目根目录（ rootPath）的“绝对路径”，于1.2.5 版本已修复。

**Comment by fangdown** [comment]
1.2.7版本 相对根目录的绝对路径还是会报错呢

**Comment by JuneAndGreen** [comment]
@fangdown 给一下 demo？
