### ISSUE TITLE
请问可以怎么mock掉wx测试工具集中的 wx 对象呢？麻烦能给一下demo吗？感谢

### ISSUE THREAD

**Issue by HhanBei** [wechat-miniprogram/miniprogram-simulate#58]
![image](https://user-images.githubusercontent.com/34788505/89412767-32f27380-d75a-11ea-86f2-7c5b963eeb67.png)
尝试按上面去设置全局对象，但是并没有生效

**Comment by JuneAndGreen** [comment]
在 require('miniprogram-simulate') 之后再设置试试呢
