### ISSUE TITLE
示例代码jest和karma测试结果不一致

### ISSUE THREAD

**Issue by Pasoul** [wechat-miniprogram/miniprogram-simulate#6]
复现步骤：
1. clone 本仓库代码并安装依赖
2. 运行npm test使用jest测试
3. 运行npm run karma使用karma测试

测试结果：
1. 使用jest
![image](https://user-images.githubusercontent.com/22902187/53081243-6543ed00-3535-11e9-9004-ccb8f97e2610.png)
2. 使用karma
![image](https://user-images.githubusercontent.com/22902187/53081278-7ab91700-3535-11e9-8c50-0faac0834523.png)

问题：
1. 为什么测试结果不一致？使用karma测试没有通过
2. karma测试时的WARN `Invalid file type, defaulting to js`怎么处理？

**Comment by JuneAndGreen** [comment]
1、因为滚动事件没有如预期的触发导致。
2、无需处理，模板相关文件会在 filemap 这个 preprocess 里处理。

**Comment by Pasoul** [comment]
好的。
