### ISSUE TITLE
请问，如何测试包含weui组件的组件

### ISSUE THREAD

**Issue by ping40** [wechat-miniprogram/miniprogram-simulate#60]
项目是通过 通过 useExtendedLib 扩展库 的方式引入weui。
我的组件one-tab.json 是：
`{
  "component": true,
  "usingComponents": {
    "mp-badge": "/miniprogram_npm/weui-miniprogram/badge/badge"
  }
}
`

npm test 出错：
`    invalid componentPath: ...\miniprogram\components\one-tab\miniprogram_npm\weui-miniprogram\badge\badge
`

npm i weui-miniprogram也没有发现weui-miniprogram目录。

simulate.render的方法中还也没有看到 mock 子组件的。

请问一下，如何测试包含weui组件的组件 ？ 

谢谢

**Comment by Tidyzq** [comment]
这里是两个问题：
1. useExtendedLib 引入的 weui 无法测试：
simulate 暂时不支持 useExtendedLib。原因是 useExtendedLib 是由小程序开发者工具去处理并且引用，而 simulate 不依赖开发者工具，因此也没有处理 useExtendedLib 的能力。可以使用 npm 安装 weui 进行测试。
2. npm i weui-miniprogram 不生效：
npm 安装完 weui 之后需要在小程序开发者工具执行 [工具]  [构建 npm]。

**Comment by Tidyzq** [comment]
另外也可以通过 mock 子组件的方式进行测试，具体方法可以参考 https://github.com/wechat-miniprogram/weui-miniprogram/blob/master/src/uploader/__test__/uploader.test.ts#L37 中如何在 mp-uploader 组件测试中将 mp-gallery 组件 mock
