### ISSUE TITLE
input组件如何测试？

### ISSUE THREAD

**Issue by anhuiliujun** [wechat-miniprogram/miniprogram-simulate#62]
input组件如何测试呢？怎样触发bindinput事件？不想通过组件实例的方式直接调用，dom上触发事件能触发bindinput吗？

**Comment by Tidyzq** [comment]
可参考 weui 的 searchbar 测试 https://github.com/wechat-miniprogram/weui-miniprogram/blob/master/src/searchbar/__test__/searchbar.test.ts
