### ISSUE TITLE
是否支持路径前缀

### ISSUE THREAD

**Issue by anhuiliujun** [wechat-miniprogram/miniprogram-simulate#63]
## 错误
```
编译 .wxml 文件错误：components/goods-live/goods-end/live-card/live-card.wxml:1:1:@/wxs/utils.wxs not found from components/goods-live/goods-end/live-card/live-card.wxml
```

## 背景
1. 在我们的wxml中会引用utils.wxs
2. 不想每次都写`../../../`
3. 所以想使用路径前缀

btw: 我可以先将小程序代码自己编译一遍，处理路径前缀，但是这样的话测试代码就只能针对编译后的去测试，我想要的是，测试代码和源码在一块

**Comment by JuneAndGreen** [comment]
目前不支持，非标准小程序写法应该交由构建工具去做，simulate 是尽量对齐到标准小程序写法的，不然以后小程序那边有类似的更新，这边提前支持了的话可能会有冲突。而且还有一个问题就是 wxs 的处理是官方 wcc 编译器做的（除非你选择内置编译器），可以认为和工具、后台用的 wcc 是差不多的，如果改造这块的话，除了代码要维护多份，还会带来实现对不齐的问题。

你这种情况，建议直接拿编译后的代码来跑。
