### ISSUE TITLE
使用jest + official 编译器后并没有渲染引用的外部组件里的template

### ISSUE THREAD

**Issue by chenzhutian** [wechat-miniprogram/miniprogram-simulate#65]
wxml代码大概如下, 然后wx:if的部分( <span wx:if="{{item.reimbursable}}" class="reimburst-label">报</span>)没有渲染.

```html
<wxs module="helper" src="../../utils/helper.wxs" />

<v-swipe-cell right-width="{{ 120 }}" left-width="{{ 0 }}">
  <v-cell custom-class="record {{customClass}}">
    <view slot="title" class="title">
      {{item.category.name}}
      <span wx:if="{{item.reimbursable}}" class="reimburst-label">报</span>
    </view>

  </v-cell>
</v-swipe-cell>

```

打印dom树出来, title节点内的结果是这样的
```html
....
              <wx-view
                class="title"
                slot="title"
              >
                
      
      
              </wx-view>
....
```

**Comment by Tidyzq** [comment]
无法复现，请提供更多信息

**Comment by chenzhutian** [comment]
@Tidyzq 
复现用的repo, npm i && npm run test
https://github.com/chenzhutian/miniprogram-simulate-minimal

**Comment by Tidyzq** [comment]
没有发现bug，请自行检查你的代码

**Comment by chenzhutian** [comment]
@Tidyzq 
![image](https://user-images.githubusercontent.com/3315274/94024707-5052ce00-fdea-11ea-9d83-a2477cdf269d.png)

这是我跑出来的结果, query出来的东西是undefined. 而预期的应该是一个     `<span class="reimburst-label">报</span>`

**Comment by chenzhutian** [comment]
相关代码在这一行
https://github.com/chenzhutian/miniprogram-simulate-minimal/blob/0753b48683e11b1674de7d6327a763d8dd3f40e5/src/components/record-item/__test__/index.spec.ts#L26

**Comment by Tidyzq** [comment]
你自己的组件参数叫做 item，你传的参数叫 records

**Comment by chenzhutian** [comment]
对喔, 解决了! 你太帅了! @Tidyzq
