### ISSUE TITLE
如果组件没有设置class和id, 是否无论如何都选不到里面的shadowTree了

### ISSUE THREAD

**Issue by chenzhutian** [wechat-miniprogram/miniprogram-simulate#67]
如题
比如外层的`v-field`可以通过id获得, 但是内层的`van-cell`既没有id也没有class, 这样是不是无论如何都选不到`van-cell`内部的元素了?
![image](https://user-images.githubusercontent.com/3315274/95657425-0a666b80-0b47-11eb-9b0a-ee518e293688.png)

**Comment by JuneAndGreen** [comment]
是的，走的接口和小程序 selectorQuery 一致：https://developers.weixin.qq.com/miniprogram/dev/api/wxml/SelectorQuery.select.html

也和小程序自定义组件实例的 selectComponent/selectAllComponents，这个文档里也有说明的。
