### ISSUE TITLE
测试input组件的时候怎么获得input的值?

### ISSUE THREAD

**Issue by chenzhutian** [wechat-miniprogram/miniprogram-simulate#69]
input在渲染的时候事先传了value进去, 但是不知道怎么取得这个值来做assertion
我试了以下几种都不行
`input.dom.innerHTML`
`input.dom.innerText`
`input.dom.getAttribute('value')`
`input.data`

谢谢

**Comment by Tidyzq** [comment]
`wx-input` 是没有 value 参数的，simulate 对 `wx-input` 的处理实际上是用了一个假的组件来代替（参考 https://github.com/wechat-miniprogram/miniprogram-simulate/blob/master/src/definition.js）
对于这种情况，建议是 assert 要传给 input 的 value 而不是 input 接收到的 value。如你的 wxml 代码是 `<view><input value="{{inputValue}}" /></view>` 则直接 `assert(comp.data.inputValue)`
