### ISSUE TITLE
如何测试page页面

### ISSUE THREAD

**Issue by funkyLover** [wechat-miniprogram/miniprogram-simulate#7]
在自定义组件章节上有[使用Component构造器构造页面](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/component.html#使用-c)的说明，所以理论上这个测试工具是否也可以用来测试页面？有没有相关指引文档？

**Comment by JuneAndGreen** [comment]
是的，页面可以当成一个最顶层的自定义组件来看待，可以直接使用此工具进行测试。

**Comment by lvsjack** [comment]
那么请问测试页面的相关代码怎么写？

**Comment by nyaapass** [comment]
@JuneAndGreen 

直接按照示例代码测试 `page` 的话, 会报 `ReferenceError: Page is not defined` 这样的错

**Comment by nyaapass** [comment]
难不成是把已有的 `Page` 页面全部改为用 `Component` 来构造, 然后才能测

这样对于已有的项目来说是不是有点太麻烦了, 后续会不会支持直接测试 `Page` 呢?

**Comment by SheldonLaw** [comment]
@nyaapass 我看目前是还没有支持Page测试的，但是Page测试和Component测试的原理其实一样，可以自己实现Page的构造函数，然后将Page的内容整理成Component的格式，再用Component构造即可，之前初略地写过一段代码，供参考：
``` js
global.Page = (options) => {
  const extraData = {};
  if (!options.methods) options.methods = {};
  Object.keys(options).forEach((key) => {
    if (key == 'methods') return;
    var value = options[key];
    //  要排除生命周期
    if (typeof value === 'function') {
      options.methods[key] = value;
    } else {
      extraData[key] = value;
    }
  });
  // 通过ready方法挂载this数据
  const oldReady = options.ready ? options.ready : ()=>{};
  options.ready = function() {
    Object.keys(extraData).forEach((key) => {
      this[key] = extraData[key];
    });
    oldReady();
  }
  global.Component(options);
};
```

其中通过ready事件来触发，将页面中的this.xxx数据挂载到实例化的Component中（官方的Component方法不会挂载this.xxx数据，仅挂载默认的几个字段）。
