### ISSUE TITLE
有类似于emitted的东西吗？

### ISSUE THREAD

**Issue by EdmundTheRadiance** [wechat-miniprogram/miniprogram-simulate#70]
组件emit要怎么测？有类似于vue的emitted的方法吗？
现在只能mock一个父组件来测吗？

**Comment by JuneAndGreen** [comment]
支持了事件监听接口：https://github.com/wechat-miniprogram/miniprogram-simulate/blob/master/docs/api.md#addeventlistenereventname-handler-usecapture

相关用例：https://github.com/wechat-miniprogram/j-component/blob/927bdc8e5441ad6dcffc30a7e34976d936b9b896/test/component.test.js#L387
