### ISSUE TITLE
invalid componentPath

### ISSUE THREAD

**Issue by 476421978** [wechat-miniprogram/miniprogram-simulate#77]
版本:
"miniprogram-simulate": "^1.4.0",
"jest": "^27.0.4",

const searchbar = simulate.load(path.resolve(__dirname, './index.wpy'))

![image](https://user-images.githubusercontent.com/38882528/121640595-b4c0d500-cac0-11eb-93da-7cc2f99f0e47.png)

**Comment by 476421978** [comment]
路径应该没问题呀，为什么找不到呢？

**Comment by JuneAndGreen** [comment]
你这是 wepy 源文件吧，这个工具只考虑原生的小程序组件，所以可以试试生成之后的代码。

**Comment by fangxxiaoming** [comment]
> 路径应该没问题呀，为什么找不到呢？

你的问题解决了嘛，我在引入的组件内部usingComponents引入绝对路径，也遇到这个问题了

**Comment by fangxxiaoming** [comment]
> 版本:
> "miniprogram-simulate": "^1.4.0",
> "jest": "^27.0.4",
> 
> const searchbar = simulate.load(path.resolve(__dirname, './index.wpy'))
> 
> ![image](https://user-images.githubusercontent.com/38882528/121640595-b4c0d500-cac0-11eb-93da-7cc2f99f0e47.png)

@JuneAndGreen

**Comment by JuneAndGreen** [comment]
@fangxxiaoming 这是 wpy，这个工具只支持原生的小程序自定义组件

**Comment by wangQiaoBrother** [comment]
配置 jest moduleNameMapper属性就可以了 https://jestjs.io/zh-Hans/docs/configuration#modulenamemapper-objectstring-string--arraystring
