### ISSUE TITLE
Uncaught ReferenceError: CustomEvent is not defined

### ISSUE THREAD

**Issue by yozosann** [wechat-miniprogram/miniprogram-simulate#82]
我自己模拟的jsdom环境，基本上都跑起来了，但是事件有问题：
![image](https://user-images.githubusercontent.com/19776974/147352701-86919b52-4753-4bcf-8b40-8de86d70e5d5.png)
有办法解决吗

**Comment by JuneAndGreen** [comment]
CustomEvent 是标准 webapi，自己模拟的环境也需要补全此 api，或者找相应的 polyfill 参考补全。
