### ISSUE TITLE
小程序页面过多导致wxml编译缓存区过大

### ISSUE THREAD

**Issue by aa875982361** [wechat-miniprogram/miniprogram-simulate#83]
共有2800多个wxml文件，编译报错如下图：

![image](https://user-images.githubusercontent.com/19383755/150768156-9fb6f782-bfdd-42a0-8975-a2a277253d1f.png)

观察报错，发现是缓存区超大小了，以至于报错。
增大缓存区，即可编译通过。
![image](https://user-images.githubusercontent.com/19383755/150768513-29bd3103-750c-44da-8a64-d0e332b32080.png)
文件位置：`miniprogram-compiler/src/wcc.js`

希望修改一下，可以动态配置缓存区大小。
或者根据组件找到依赖到的wxml wxs，不全量编译。

**Comment by JuneAndGreen** [comment]
https://github.com/wechat-miniprogram/miniprogram-simulate/blob/master/docs/api.md#options

![image](https://user-images.githubusercontent.com/7931744/150772468-e3893ff3-c1ee-4bb5-880d-6c07af51ab47.png)

动态调整缓存大小我看看，不过这里可以调整目录的，本工具作为组件单测使用，建议按目录传入以免全量编译。

**Comment by aa875982361** [comment]
@JuneAndGreen 有看到的，但是因为组件引用路径是全局的，所以必须要设置rootPath为小程序的。
比如说组件.json:
`
{
  "usingComponents": {
    "compa":"/pages/components/compa"
  }
}
`
修改源代码也可以，但是改动会比较大

**Comment by JuneAndGreen** [comment]
这个其实也可以在调 load 的时候改掉的，这样就不会因为 usingComponents 而导致必须使用大范围的 rootPath：

![image](https://user-images.githubusercontent.com/7931744/150899813-49df8f91-f098-411e-9d83-d28e0c49d002.png)

**Comment by aa875982361** [comment]
@JuneAndGreen 我试了，是可以的，感谢。但是如果有引用到wxs，就会报错找不到wxs，因为wxs并不是在组件下面。
能否让用户传入需要的wxml 和 wxs 文件路径列表？我看底层实现是找根目录下的全部wxml和wxs
比如说我通过分析wxml 和 json 文件，找到依赖的wxml和wxs文件路径，然后通过配置传进去?

**Comment by JuneAndGreen** [comment]
emmm，这情况比较麻烦。

wxs 目前做不到，主要 wxs、wxss 和 wxml import 的路径处理都是由 wcsc 和 wcc 来处理的，这两个用的和工具用的编译器是同一个，我这边只是直接借用编译器无法侵入去改造。

**Comment by aa875982361** [comment]
@JuneAndGreen 我这边有个想法不知道行不行。
我看了miniprogram-compiler的wxmlToJs逻辑，里面遍历了全量wxml 和wxs，拿到wxmlList 和 wxsList 
如果可以修改这个库的逻辑的话，那是不是就可以通过外部传入wxmlList 和 wxsList。
![image](https://user-images.githubusercontent.com/19383755/150932979-19607de3-ed5d-42ad-9d4d-b4212f89b1ca.png)
然后在外部去分析组件依赖的wxml，和wxs，得到wxmlList和wxsList。
不知道这样行不行。

**Comment by aa875982361** [comment]
https://github.com/wechat-miniprogram/miniprogram-simulate/pull/84/files
这是我做的处理，可以看一下

**Comment by JuneAndGreen** [comment]
miniprogram-simulate@1.5.0

![image](https://user-images.githubusercontent.com/7931744/154427434-0ff93728-6e6a-4382-b628-52a9348d792c.png)

支持了编译的一些配置，应该可以满足你的需求了，可参考 demo10。

**Comment by aa875982361** [comment]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/19383755/154636356-782b5c35-c06b-41e3-ac8b-91980c0a144a.png">
@JuneAndGreen  可以问下这里是忘记更新么？

**Comment by JuneAndGreen** [comment]
> <img alt="image" width="927" src="https://user-images.githubusercontent.com/19383755/154636356-782b5c35-c06b-41e3-ac8b-91980c0a144a.png">
> 
> @JuneAndGreen 可以问下这里是忘记更新么？

噢，是的，这份之前是其他同学帮忙弄的，我这边遗漏了。

**Comment by JuneAndGreen** [comment]
改了 miniprogram-simulate@1.5.1，再试试看？

**Comment by JuneAndGreen** [comment]
这个需要负责编译器的同事来优化才行，之前听说是有计划做重构的，不过可能不会那么快完成。

**Comment by JuneAndGreen** [comment]
可以的，我记一下。

**Comment by JuneAndGreen** [comment]
> 可以了 感谢~ 对了，之前在排查问题的时候，花了比较久的时间才排查到时因为缓存区的问题，感觉有时间可以优化一下。 我之前是通过打断点的方式找到错误的，比较麻烦。 <img alt="image" width="1043" src="https://user-images.githubusercontent.com/19383755/154641792-d35cba62-ac80-46b9-9aea-be55ebc3e6aa.png">

miniprogram-compiler@0.2.1 补充了，会将 spawnSync 的异常直接抛出来
