### ISSUE TITLE
wxs后缀的文件不支持吗

### ISSUE THREAD

**Issue by wuyanwen** [wechat-miniprogram/miniprogram-simulate#85]
编译 .wxml 文件错误：banner.wxml:2:1:../../common/js/wxs/set-price-mark.wxs not found from banner.wxml

**Comment by JuneAndGreen** [comment]
支持，但是目前必须在编译目录下，通过 rootPath 参数可以修改编译目录：

![image](https://user-images.githubusercontent.com/7931744/151094217-1fb0ed33-f971-4bdb-b2bd-74cb2ed8488e.png)

https://github.com/wechat-miniprogram/miniprogram-simulate/blob/master/docs/api.md#options
