### ISSUE TITLE
wx.getAccountInfoSync().miniProgram.envVersion报错问题

### ISSUE THREAD

**Issue by wuyanwen** [wechat-miniprogram/miniprogram-simulate#87]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/7331663/152749567-51b83d0f-91f4-417f-bf7c-a7cbc6753d96.png">

**Comment by wuyanwen** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/7331663/152767519-3f3a1128-30a2-4940-94d3-98b3543c118a.png">
按照这样mock了下，也不行

**Comment by JuneAndGreen** [comment]
试了下没问题，你是不是 mock 时间晚于执行时间了？把 mock 放到用例最开始的地方试试？

**Comment by aa875982361** [comment]
@JuneAndGreen 之前有遇到过类似的问题。我看了一下代码，引入simulate的时候，会重新覆盖一遍global.wx，
`import * as simulate from 'miniprogram-simulate'`
具体在miniprogram-simulate/src/index.js 第九行
`const injectDefinition = require('./definition')`
在miniprogram-simulate/src/definition.js 第27行
`global.wx = api`
假设我再执行单元测试脚本之前，先写了global.wx = {}
然后再单元测试脚本运行的时候再引入simulate， 就会重写掉global.wx

**Comment by aa875982361** [comment]
目前我的解决办法如下：
`Object.defineProperty(global, "wx", {
  get(){
    return globalWx
  },
  set(newValue: any): void{
    console.log("设置global.wx 没用 被我劫持了")
  },
});`

**Comment by JuneAndGreen** [comment]
> @JuneAndGreen 之前有遇到过类似的问题。我看了一下代码，引入simulate的时候，会重新覆盖一遍global.wx， `import * as simulate from 'miniprogram-simulate'` 具体在miniprogram-simulate/src/index.js 第九行 `const injectDefinition = require('./definition')` 在miniprogram-simulate/src/definition.js 第27行 `global.wx = api` 假设我再执行单元测试脚本之前，先写了global.wx = {} 然后再单元测试脚本运行的时候再引入simulate， 就会重写掉global.wx

修复了一下到，miniprogram-simulate@1.5.5，如果 global.wx 是个对象就进行浅拷贝。

**Comment by aa875982361** [comment]
@JuneAndGreen 看了一下代码 好像判断写错了， ` typeof global.wx === "function"`？
