### ISSUE TITLE
使用插件导致编译出错

### ISSUE THREAD

**Issue by aa875982361** [wechat-miniprogram/miniprogram-simulate#89]
一个组件使用了插件：plugin://chatGroupPlugin/cell，编译会提示找不到这个组件
`{
  "component": true,
  "usingComponents": {
    "cell": "plugin://chatGroupPlugin/cell"
  }
}
`
错误提示：
`invalid componentPath: /uest/xxxxx/xxxx/components/compA/plugin:/chatGroupPlugin/cell`

**Comment by aa875982361** [comment]
对于这些插件能否使用一个占位view来渲染？只需要知道这些插件组件能正常渲染即可。

**Comment by JuneAndGreen** [comment]
https://github.com/wechat-miniprogram/miniprogram-simulate/blob/master/docs/api.md#loadcomponentpath-tagname-options--loaddefinition

可以使用 usingComponents 手动替换掉。

**Comment by aa875982361** [comment]
@JuneAndGreen 如果是组件在内部嵌套结构里面，就没办法使用这个配置替换。
比如说：组件A引用组件B，组件B使用插件组件
在load组件A的时候传入usingComponents，不能替换掉组件B使用的插件。
上面说的情况是只有一层，真实情况会有多层

**Comment by JuneAndGreen** [comment]
miniprogram-simulate@1.5.3 其实原本的 usingComponents 覆盖就支持覆盖掉子孙的 usingComponents 的，不过之前只支持传组件 id，现在完善了下，也支持传路径。

可参考 comp11.

**Comment by aa875982361** [comment]
好的 谢谢
