### ISSUE TITLE
getStorageSync 套了一层JSON.parse，传入如果存入字符串，获取就会报错

### ISSUE THREAD

**Issue by cjinhuo** [wechat-miniprogram/miniprogram-simulate#90]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/22608658/167346457-c204a0bf-6d75-4aae-b37e-932126484295.png">

**Comment by cjinhuo** [comment]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/22608658/167346956-a3b5097e-8f79-47d1-b75b-e45fd442fb58.png">

**Comment by cjinhuo** [comment]
> <img alt="image" width="581" src="https://user-images.githubusercontent.com/22608658/167346956-a3b5097e-8f79-47d1-b75b-e45fd442fb58.png">

这样写如何？

**Comment by JuneAndGreen** [comment]
fixed 到: miniprogram-simulate@1.5.6
