### ISSUE TITLE
TypeError: wx.nextTick is not a function

### ISSUE THREAD

**Issue by missannil** [wechat-miniprogram/miniprogram-simulate#91]
ts-jest中 组件包含  wx.nextTick 时报错！
"TypeError: wx.nextTick is not a function"

**Comment by JuneAndGreen** [comment]
miniprogram-simulate@1.5.7

wx.nextTick 是和组件有点关联的接口所以补了下。不过如果是非组件相关的接口，后续 miniprogram-simulate 就不再补充了，开发者可以自己在 global.wx 上进行扩展覆盖或补充，以便进行各种不同场景的测试。
